// Test-case loader and matcher for data-driven test suites.
// YAML case files live under test/cases/<phase>/*.yaml.

import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { load } from 'js-yaml';

// ─── translator cases ────────────────────────────────────────────────────

export type TranslatorCase = {
  desc: string;
  /** Partial StructureDefinition. Merged into `defaults.sd` from the file. */
  sd: Record<string, unknown>;
  /** Partial expected FHIRSchema (subset match). Mutually exclusive with `throws`. */
  expected?: Record<string, unknown>;
  /** Substring of error message expected on translate(). */
  throws?: string;
  only?: boolean;
  skip?: boolean;
};

export type TranslatorSuite = {
  suite: string;
  defaults?: { sd?: Record<string, unknown> };
  tests: TranslatorCase[];
};

// ─── validator cases ─────────────────────────────────────────────────────

export type ValidatorCase = {
  desc: string;
  /** FHIRSchemas passed as the second arg to validate(). */
  schemas: Record<string, unknown>[];
  /** Resource / value to validate. */
  data: unknown;
  /** Options forwarded as the 4th arg to validate(). */
  options?: Record<string, unknown>;
  /**
   * Schemas to register in the test ctx. Resolution keys: each schema's `url`,
   * `name`, and `type` are all registered. Caller can override per-case via
   * `defaults.registry` from the file.
   */
  registry?: Record<string, unknown>[];
  /**
   * Expected issues. The matcher requires each entry in `issues` to find a
   * matching issue in the actual output (subset on issue fields). Extra issues
   * in the actual output cause failure — assert all expected codes are present
   * AND no surprise codes appear.
   */
  issues?: Array<{
    code: string;
    path?: (string | number)[] | string;
    expected?: unknown;
    got?: unknown;
  }>;
  /** Shortcut for { issues: [] }. */
  valid?: boolean;
  only?: boolean;
  skip?: boolean;
};

export type ValidatorSuite = {
  suite: string;
  defaults?: {
    /** Schemas auto-registered in the resolver context for every test. */
    registry?: Record<string, unknown>[];
    /** Shortcut: auto-load hl7.fhir.r4.core into ctx. */
    useR4?: boolean;
    /** Generic: load any number of prepared packages by id. */
    usePackages?: string[];
    /** Wire HL7 fhirpath.js into `options.fhirpath` for constraint eval. */
    useFhirpath?: boolean;
    /** Wire a test terminology evaluator (urn:vs:colors → red/green/blue). */
    useTerminology?: boolean;
    /** Wire the live tx.health-samurai.io adapter (sync HTTP via curl). */
    useTxServer?: boolean;
    /** Wire a test reference resolver (knows Patient/1, Patient/2, Organization/org1). */
    useReferenceResolver?: boolean;
  };
  tests: ValidatorCase[];
};

// ─── generic ─────────────────────────────────────────────────────────────

export type SuiteFile<S = TranslatorSuite | ValidatorSuite> = {
  /** Relative file name without extension, e.g. "cardinality". */
  name: string;
  /** Full absolute path. */
  path: string;
  suite: S;
};

/** Load every *.yaml under a directory (recursive). */
export function loadSuites<S = TranslatorSuite>(dir: string): SuiteFile<S>[] {
  const out: SuiteFile<S>[] = [];
  for (const entry of readdirSync(dir).sort()) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...loadSuites<S>(full));
      continue;
    }
    if (!entry.endsWith('.yaml') && !entry.endsWith('.yml')) continue;
    const suite = load(readFileSync(full, 'utf8')) as S;
    const tests = (suite as unknown as { tests?: unknown[] })?.tests;
    if (!suite || !Array.isArray(tests)) {
      throw new Error(`Invalid suite file (missing tests[]): ${full}`);
    }
    out.push({
      name: entry.replace(/\.ya?ml$/, ''),
      path: full,
      suite,
    });
  }
  return out;
}

/** Deep-merge `b` into `a`; arrays are replaced, not concatenated. */
export function deepMerge<T extends Record<string, unknown>>(a: T, b: T): T {
  const out: Record<string, unknown> = { ...a };
  for (const k of Object.keys(b)) {
    const av = (a as Record<string, unknown>)[k];
    const bv = (b as Record<string, unknown>)[k];
    if (isPlainObject(av) && isPlainObject(bv)) {
      out[k] = deepMerge(av, bv);
    } else {
      out[k] = bv;
    }
  }
  return out as T;
}

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return v !== null && typeof v === 'object' && !Array.isArray(v);
}

// ─── FHIR package fixtures ───────────────────────────────────────────────

import type { FHIRSchema, StructureDefinition } from '../src/converter/types.js';
import { translate } from '../src/converter/index.js';
import { XMLParser } from 'fast-xml-parser';

const FIXTURES_ROOT = join(import.meta.dir, 'fixtures');

let _r4Cache: FHIRSchema[] | undefined;

/**
 * Load every FHIRSchema from test/fixtures/<pkg>/. Cached per-process.
 * The fixtures are generated by `bun run prepare-fixtures` (auto-run on
 * `bun test` via the `pretest` script).
 */
export function loadPackageFixtures(pkgId: string): FHIRSchema[] {
  if (pkgId === 'hl7.fhir.r4.core' && _r4Cache) return _r4Cache;

  // Accept both bare id (core packages) and `id@version` (others).
  const dir = join(FIXTURES_ROOT, pkgId);
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    throw new Error(
      `Fixtures for ${pkgId} not prepared. Run: bun run prepare-fixtures`,
    );
  }
  const out: FHIRSchema[] = [];
  for (const f of entries) {
    if (!f.endsWith('.fs.json')) continue;
    out.push(JSON.parse(readFileSync(join(dir, f), 'utf8')) as FHIRSchema);
  }
  if (pkgId === 'hl7.fhir.r4.core') _r4Cache = out;
  return out;
}

/**
 * Load a FHIR StructureDefinition file (relative to fhir-test-cases/validator)
 * and translate it on-the-fly to a FHIRSchema. Used by Graham profile-loading
 * cases that ship custom SDs alongside test data.
 */
const FHIR_TEST_CASES_ROOT = join(import.meta.dir, '..', '..', 'fhir-test-cases', 'validator');
const _profileCache = new Map<string, FHIRSchema>();

export function loadProfileSchema(relPath: string): FHIRSchema {
  const cached = _profileCache.get(relPath);
  if (cached) return cached;
  const full = join(FHIR_TEST_CASES_ROOT, relPath);
  let raw: string;
  try {
    raw = readFileSync(full, 'utf8');
  } catch {
    throw new Error(`profile file not found: ${full}`);
  }
  const sd: StructureDefinition = relPath.endsWith('.xml')
    ? (fhirXmlToJson(raw) as StructureDefinition)
    : (JSON.parse(raw) as StructureDefinition);
  const schema = translate(sd);
  _profileCache.set(relPath, schema);
  return schema;
}

// FHIR fields that are always arrays inside an ElementDefinition (or
// other deep contexts) even when only one occurrence is present. We use
// the jpath argument to gate — only force-array when we're under the
// `differential.element[]` / `snapshot.element[]` path, plus a couple
// of top-level always-array fields. FHIR JSON spec says single-instance
// still needs the [] wrapper for these.
const ELEMENT_ARRAY_FIELDS = new Set([
  'type', 'constraint', 'discriminator', 'extension', 'modifierExtension',
  'representation', 'code', 'mapping', 'alias', 'targetProfile', 'profile',
]);
const ALWAYS_ARRAY_FIELDS = new Set([
  'element', 'identifier', 'contact', 'useContext', 'jurisdiction',
]);
const _xmlParser = new XMLParser({
  ignoreAttributes: false,
  attributeNamePrefix: '@',
  parseAttributeValue: false,
  parseTagValue: false,
  isArray: (name, jpath) => {
    if (ALWAYS_ARRAY_FIELDS.has(name)) return true;
    if (ELEMENT_ARRAY_FIELDS.has(name) && /\.element(\.|$)/.test(String(jpath))) return true;
    return false;
  },
});

/**
 * Convert FHIR XML (single root element under `<StructureDefinition>` etc.)
 * to the FHIR JSON shape our translator consumes.
 *
 * Conventions:
 * - Every primitive is `<element value="X"/>` → `"element": "X"`
 * - Wrapper elements (`<element>...</element>`) → nested object
 * - Sibling repeats become arrays (fast-xml-parser already does this)
 * - `xmlns`, `?xml`, and other meta attrs are dropped
 */
function fhirXmlToJson(xml: string): unknown {
  const parsed = _xmlParser.parse(xml) as Record<string, unknown>;
  // Drop the XML declaration; find the first non-meta root.
  let root: Record<string, unknown> | undefined;
  let rootName: string | undefined;
  for (const [k, v] of Object.entries(parsed)) {
    if (k.startsWith('?')) continue;
    root = v as Record<string, unknown>;
    rootName = k;
    break;
  }
  if (!root || !rootName) throw new Error('no XML root element found');
  const json = collapseFhirNode(root);
  if (typeof json === 'object' && json !== null) {
    (json as Record<string, unknown>).resourceType = rootName;
  }
  return json;
}

function collapseFhirNode(node: unknown): unknown {
  if (node === null || node === undefined) return node;
  if (Array.isArray(node)) return node.map(collapseFhirNode);
  if (typeof node !== 'object') return node;
  const obj = node as Record<string, unknown>;
  const keys = Object.keys(obj);
  // Primitive: `<el value="X"/>` parses to `{@value: "X"}` (possibly with
  // other attrs we ignore). Collapse to the bare value.
  if ('@value' in obj && keys.every((k) => k.startsWith('@'))) {
    return obj['@value'];
  }
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith('@')) continue; // drop other attributes (xmlns etc.)
    if (k === '#text') continue;
    out[k] = collapseFhirNode(v);
  }
  return out;
}

/**
 * Build a resolver map keyed by `url`, `name`, and (for base schemas only)
 * `type`. A schema is treated as the canonical for its `type` only when
 * `name === type` — otherwise it's a profile whose type-key would shadow
 * the real base (e.g. an Observation profile would otherwise register under
 * "Observation" and outrank the base).
 */
export function buildResolverMap(schemas: FHIRSchema[]): Map<string, FHIRSchema> {
  const map = new Map<string, FHIRSchema>();
  for (const s of schemas) {
    const keys = [s.url, s.name];
    if (s.name === s.type) keys.push(s.type);
    for (const k of keys) {
      if (typeof k === 'string' && k.length > 0 && !map.has(k)) map.set(k, s);
    }
  }
  return map;
}

/**
 * Deep-subset match: every key in `expected` must exist in `actual` and
 * deep-match. Extra keys in `actual` are allowed. Arrays must match length
 * and order. Returns null on match, otherwise a human-readable mismatch path.
 */
export function subsetMatch(expected: unknown, actual: unknown, path: string = ''): string | null {
  if (Array.isArray(expected)) {
    if (!Array.isArray(actual)) return `${path}: expected array, got ${typeof actual}`;
    if (expected.length !== actual.length)
      return `${path}: array length ${actual.length}, expected ${expected.length}`;
    for (let i = 0; i < expected.length; i++) {
      const m = subsetMatch(expected[i], actual[i], `${path}[${i}]`);
      if (m) return m;
    }
    return null;
  }
  if (isPlainObject(expected)) {
    if (!isPlainObject(actual)) return `${path}: expected object, got ${typeof actual}`;
    for (const k of Object.keys(expected)) {
      const m = subsetMatch(expected[k], actual[k], path ? `${path}.${k}` : k);
      if (m) return m;
    }
    return null;
  }
  // primitives — strict equality
  if (expected !== actual) {
    return `${path}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`;
  }
  return null;
}
