name: format check

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Biome - Format Check
        run: bun run format

      - name: Biome - Lint
        run: bun run lint

      - name: Run tests
        run: bun test
